"""
Feature schema and data types for synthetic loan application simulation.

- Feature names are modeled after standard structured datasets in credit scoring domains.
- All values are synthetic, randomly generated, and not based on any real-world data.
- This module supports realistic data simulation for ML demo purposes only.

No proprietary or competition datasets are used.
"""


# —————————————————————————————————————————
# 1) DEFINE RAW SCHEMA & DTYPE MAPS
# —————————————————————————————————————————
RAW_SCHEMA = {
    "customer_profile": [
        "CUSTOMER_ID",
        "TARGET",
        "LOAN_CONTRACT_TYPE",
        "GENDER_CODE",
        "OWNS_CAR",
        "OWNS_PROPERTY",
        "NUM_CHILDREN",
        "MONTHLY_INCOME",
        "LOAN_AMOUNT",
        "LOAN_TERM_MONTHS", 
        "LOAN_ANNUITY",
        "PURCHASED_GOODS_VALUE",
        "ACCOMPANIED_BY",
        "INCOME_SOURCE_TYPE",
        "EDUCATION_LEVEL",
        "FAMILY_STATUS",
        "HOUSING_TYPE",
        "REGION_POPULATION_RATIO",
        "AGE_DAYS",
        "EMPLOYMENT_DURATION_DAYS",
        "DAYS_SINCE_REGISTRATION",
        "DAYS_SINCE_ID_ISSUE",
        "HAS_MOBILE",
        "HAS_WORK_PHONE",
        "HAS_SECONDARY_PHONE",
        "MOBILE_ACTIVE",
        "HAS_LANDLINE_PHONE",
        "HAS_EMAIL",
        "OCCUPATION_TYPE",
        "NUM_FAMILY_MEMBERS",
        "REGION_SCORE",
        "REGION_CITY_SCORE",
        "APPLICATION_DAY_OF_WEEK",
        "APPLICATION_HOUR",
        "RESIDES_IN_REGISTERED_REGION",
        "WORKS_IN_REGISTERED_REGION",
        "SAME_REGION_WORK_LIVE",
        "RESIDES_IN_REGISTERED_CITY",
        "WORKS_IN_REGISTERED_CITY",
        "SAME_CITY_WORK_LIVE",
        "EMPLOYER_CATEGORY",
        "EXTERNAL_CREDIT_SCORE",
        "SECONDARY_CREDIT_SCORE",
        "BUILD_YEAR_AVG",
        "MAX_FLOORS_AVG",
        "BUILD_YEAR_MODE",
        "MAX_FLOORS_MODE",
        "BUILD_YEAR_MEDIAN",
        "MAX_FLOORS_MEDIAN",
        "PROPERTY_TOTAL_AREA",
        "DAYS_SINCE_LAST_PHONE_CHANGE",
    ],

    "credit_summary": [
        "CUSTOMER_ID",
        "CREDIT_RECORD_ID",
        "CREDIT_STATUS",
        "CURRENCY_TYPE",
        "DAYS_SINCE_CREDIT_ISSUED",
        "DAYS_OVERDUE",
        "DAYS_UNTIL_CREDIT_END",
        "DAYS_UNTIL_ACTUAL_CREDIT_CLOSED",
        "NUM_CREDIT_EXTENSIONS",
        "TOTAL_CREDIT_AMOUNT",
        "OUTSTANDING_DEBT",
        "CREDIT_LIMIT",
        "OVERDUE_BALANCE",
        "TYPE_OF_CREDIT",
        "DAYS_SINCE_CREDIT_UPDATE",
    ],
    "credit_timeline": [
        "CREDIT_RECORD_ID",
        "TIME_SINCE_ENTRY",
        "ACCOUNT_STATUS",
    ],
    "card_activity": [
        "PRIOR_LOAN_ID",
        "CUSTOMER_ID",
        "TIME_SINCE_ENTRY",
        "CURRENT_CARD_BALANCE",
        "CARD_CREDIT_LIMIT",
        "CASH_WITHDRAWN_ATM",
        "TOTAL_WITHDRAWN_AMOUNT",
        "WITHDRAWN_OTHER_CHANNELS",
        "PURCHASES_POS",
        "MINIMUM_PAYMENT_DUE",
        "CURRENT_PAYMENT",
        "TOTAL_PAYMENT",
        "PRINCIPAL_DUE",
        "RECEIVABLE_BALANCE",
        "TOTAL_RECEIVABLE",
        "ATM_WITHDRAWAL_COUNT",
        "TOTAL_WITHDRAWAL_COUNT",
        "OTHER_WITHDRAWAL_COUNT",
        "POS_PURCHASE_COUNT",
        "TOTAL_INSTALLMENTS_PAID",
        "CONTRACT_STATUS",
        "DAYS_PAST_DUE",
        "DAYS_PAST_DUE_90",
    ],
    "cash_pos_records": [
        "PRIOR_LOAN_ID",
        "CUSTOMER_ID",
        "TIME_SINCE_ENTRY",
        "LOAN_TERM_MONTHS",
        "REMAINING_TERM_MONTHS",
        "CONTRACT_STATUS",
        "DAYS_PAST_DUE",
        "DAYS_PAST_DUE_90",
    ],
    "installment_records": [
        "PRIOR_LOAN_ID",
        "CUSTOMER_ID",
        "INSTALLMENT_PLAN_VERSION",
        "INSTALLMENT_SEQUENCE_NUMBER",
        "DAYS_UNTIL_DUE",
        "DAYS_BEFORE_ACTUAL_PAYMENT",
        "SCHEDULED_PAYMENT_AMOUNT",
        "ACTUAL_PAYMENT_AMOUNT",
    ],
    "prior_loan_history": [
        "PRIOR_LOAN_ID",
        "CUSTOMER_ID",
        "LOAN_CONTRACT_TYPE",
        "LOAN_ANNUITY",
        "REQUESTED_LOAN_AMOUNT",
        "LOAN_AMOUNT",
        "PURCHASED_GOODS_VALUE",
        "APPLICATION_DAY_OF_WEEK",
        "APPLICATION_HOUR",
        "IS_LAST_APPLICATION_FOR_CONTRACT",
        "IS_LAST_APPLICATION_OF_DAY",
        "LOAN_PURPOSE_CATEGORY",
        "CONTRACT_STATUS",
        "DAYS_SINCE_DECISION",
        "PAYMENT_METHOD",
        "REJECTION_REASON_CODE",
        "ACCOMPANIED_BY",
        "CLIENT_TYPE",
        "PORTFOLIO_TYPE",
        "APPLICATION_CHANNEL",
        "BRANCH_AREA_CODE",
        "PLANNED_NUM_PAYMENTS",
        "YIELD_CATEGORY",
        "PRODUCT_BUNDLE_TYPE",
        "DAYS_UNTIL_FIRST_DRAW",
        "DAYS_UNTIL_FIRST_PAYMENT",
        "DAYS_UNTIL_FINAL_PAYMENT",
        "DAYS_UNTIL_TERMINATION",
        "IS_INSURED_ON_APPROVAL",
    ],
}


DTYPE_MAP = {
    "CUSTOMER_ID":         "int64",
    "TARGET":              "Int64",
    "LOAN_CONTRACT_TYPE":  "category",
    "GENDER_CODE":         "category",
    "OWNS_CAR":            "category",
    "OWNS_PROPERTY":       "category",
    "NUM_CHILDREN":        "Int64",
    "MONTHLY_INCOME":      "float64",
    "LOAN_AMOUNT":          "float64",
    "LOAN_ANNUITY":         "float64",
    "PURCHASED_GOODS_VALUE":     "float64",
    "ACCOMPANIED_BY":             "category",
    "INCOME_SOURCE_TYPE":         "category",
    "EDUCATION_LEVEL":            "category",
    "FAMILY_STATUS":              "category",
    "HOUSING_TYPE":               "category",
    "REGION_POPULATION_RATIO":    "float64",
    "AGE_DAYS":                   "int64",
    "EMPLOYMENT_DURATION_DAYS":   "int64",
    "DAYS_SINCE_REGISTRATION":    "float64",
    "DAYS_SINCE_ID_ISSUE":        "int64",
    "HAS_MOBILE":                 "category",
    "HAS_WORK_PHONE":             "category",
    "HAS_SECONDARY_PHONE":        "category",
    "MOBILE_ACTIVE":              "category",
    "HAS_LANDLINE_PHONE":         "category",
    "HAS_EMAIL":                  "category",
    "OCCUPATION_TYPE":              "category",
    "NUM_FAMILY_MEMBERS":           "Int64",
    "REGION_SCORE":                 "Int64",
    "REGION_CITY_SCORE":  "Int64",
    "APPLICATION_DAY_OF_WEEK":      "category",
    "APPLICATION_HOUR":      "int64",
    "RESIDES_IN_REGISTERED_REGION":   "category",
    "WORKS_IN_REGISTERED_REGION":   "category",
    "SAME_REGION_WORK_LIVE":  "category",
    "RESIDES_IN_REGISTERED_CITY":   "category",
    "WORKS_IN_REGISTERED_CITY":       "category",
    "SAME_CITY_WORK_LIVE":          "category",
    "EMPLOYER_CATEGORY":            "category",
    "EXTERNAL_CREDIT_SCORE":        "float64",
    "SECONDARY_CREDIT_SCORE":       "float64",
    "BUILD_YEAR_AVG":               "float64",
    "MAX_FLOORS_AVG":               "float64",
    "BUILD_YEAR_MODE":              "float64",
    "MAX_FLOORS_MODE":              "float64",
    "BUILD_YEAR_MEDIAN":            "float64",
    "MAX_FLOORS_MEDIAN":            "float64",
    "PROPERTY_TOTAL_AREA":          "float64",
    "DAYS_SINCE_LAST_PHONE_CHANGE": "Int64",

    "CREDIT_RECORD_ID":            "int64",
    "CREDIT_STATUS":               "category",
    "CURRENCY_TYPE":               "category",
    "DAYS_SINCE_CREDIT_ISSUED":    "int64",
    "DAYS_OVERDUE":                "int64",
    "DAYS_UNTIL_CREDIT_END":       "float64",
    "DAYS_UNTIL_ACTUAL_CREDIT_CLOSED": "float64",
    "NUM_CREDIT_EXTENSIONS":          "category",
    "TOTAL_CREDIT_AMOUNT":         "float64",
    "OUTSTANDING_DEBT":            "float64",
    "CREDIT_LIMIT":                "float64",
    "OVERDUE_BALANCE":             "float64",
    "TYPE_OF_CREDIT":              "category",
    "DAYS_SINCE_CREDIT_UPDATE":    "int64",

    "TIME_SINCE_ENTRY":             "int64",
    "ACCOUNT_STATUS":               "category",

    "PRIOR_LOAN_ID":                "int64",
    "CUSTOMER_ID":                   "int64",
    "CURRENT_CARD_BALANCE":          "float64",
    "CARD_CREDIT_LIMIT":            "int64",
    "CASH_WITHDRAWN_ATM":           "float64",
    "TOTAL_WITHDRAWN_AMOUNT":       "float64",
    "WITHDRAWN_OTHER_CHANNELS":     "float64",
    "PURCHASES_POS":                "float64",
    "MINIMUM_PAYMENT_DUE":          "float64",
    "CURRENT_PAYMENT":              "float64",
    "TOTAL_PAYMENT":                "float64",
    "PRINCIPAL_DUE":                "float64",
    "RECEIVABLE_BALANCE":           "float64",
    "TOTAL_RECEIVABLE":             "float64",
    "ATM_WITHDRAWAL_COUNT":         "Int64",
    "TOTAL_WITHDRAWAL_COUNT":       "int64",
    "OTHER_WITHDRAWAL_COUNT":       "Int64",
    "POS_PURCHASE_COUNT":           "Int64",
    "TOTAL_INSTALLMENTS_PAID":      "Int64",
    "CONTRACT_STATUS":              "category",
    "DAYS_PAST_DUE":                "int64",
    "DAYS_PAST_DUE_90":             "int64",

    "PRIOR_LOAN_ID":               "int64",
    "CUSTOMER_ID":                  "int64",
    "LOAN_TERM_MONTHS":              "Int64",
    "REMAINING_TERM_MONTHS":       "Int64",
    "CONTRACT_STATUS":             "category",
    "DAYS_PAST_DUE":               "int64",
    "DAYS_PAST_DUE_90":            "int64",

    "INSTALLMENT_PLAN_VERSION":    "Int64",
    "INSTALLMENT_SEQUENCE_NUMBER": "int64",
    "DAYS_UNTIL_DUE":              "Int64",
    "DAYS_BEFORE_ACTUAL_PAYMENT":  "Int64",
    "SCHEDULED_PAYMENT_AMOUNT":    "float64",
    "ACTUAL_PAYMENT_AMOUNT":       "float64",

    "LOAN_CONTRACT_TYPE":          "category",
    "LOAN_ANNUITY":                "float64",
    "REQUESTED_LOAN_AMOUNT":       "float64",
    "LOAN_AMOUNT":                 "float64",
    "PURCHASED_GOODS_VALUE":       "float64",
    "APPLICATION_DAY_OF_WEEK":     "category",
    "APPLICATION_HOUR":     "int64",
    "IS_LAST_APPLICATION_FOR_CONTRACT": "category",
    "IS_LAST_APPLICATION_OF_DAY":  "category",
    "LOAN_PURPOSE_CATEGORY":      "category",
    "CONTRACT_STATUS":             "category",
    "DAYS_SINCE_DECISION":         "int64",
    "PAYMENT_METHOD":             "category",
    "REJECTION_REASON_CODE":      "category",
    "ACCOMPANIED_BY":             "category",
    "CLIENT_TYPE":                "category",
    "PORTFOLIO_TYPE":             "category",
    "APPLICATION_CHANNEL":        "category",
    "BRANCH_AREA_CODE":           "int64",
    "PLANNED_NUM_PAYMENTS":       "float64",
    "YIELD_CATEGORY":             "category",
    "PRODUCT_BUNDLE_TYPE":        "category",
    "DAYS_UNTIL_FIRST_DRAW":      "float64",
    "DAYS_UNTIL_FIRST_PAYMENT":   "float64",
    "DAYS_UNTIL_FINAL_PAYMENT":   "float64",
    "DAYS_UNTIL_TERMINATION":     "float64",
    "IS_INSURED_ON_APPROVAL":     "category",

}


DEFAULT_CATS = {
    "LOAN_CONTRACT_TYPE":       ["Loan Type A", "Loan Type B"],
    "GENDER_CODE":              ["Alpha", "Beta"],
    "OWNS_CAR":                 ["Yes", "No"],
    "OWNS_PROPERTY":            ["True", "False"],
    "ACCOMPANIED_BY":           ["Single", "Partner", "Group"],
    "INCOME_SOURCE_TYPE":       ["Income A", "Income B", "Income C", "Income D"],
    "EDUCATION_LEVEL":          ["Education X", "Education Y", "Education Z", "Unknown"],
    "FAMILY_STATUS":            ["Status A", "Status B", "Status C", "Status D"],
    "HOUSING_TYPE":               ["Housing A", "Housing B", "Housing C", "Other"],
    "APPLICATION_DAY_OF_WEEK":    ["Day A", "Day B", "Day C", "Day D", "Day E"],
    "RESIDES_IN_REGISTERED_REGION": ["Y", "N"],
    "WORKS_IN_REGISTERED_REGION":   ["Y", "N"],
    "SAME_REGION_WORK_LIVE":        ["Y", "N"],
    "RESIDES_IN_REGISTERED_CITY":   ["Y", "N"],
    "WORKS_IN_REGISTERED_CITY":   ["Y", "N"],
    "SAME_CITY_WORK_LIVE":      ["Y", "N"],
    "OCCUPATION_TYPE":          ["Job A", "Job B", "Job C", "Job D", "Job E"],
    "EMPLOYER_CATEGORY":        ["Org X", "Org Y", "Org Z", "Entity M", "Entity N"],
    "DEF_30_CNT_SOCIAL_CIRCLE": ["None", "Few", "Many"],
    "DEF_60_CNT_SOCIAL_CIRCLE": ["None", "Some", "Several"],
    "FLAG_DOCUMENT_2":          ["No", "Yes"],
    "FLAG_DOCUMENT_3":          ["No", "Yes"],
    "FLAG_DOCUMENT_4":          ["No", "Yes"],
    "FLAG_DOCUMENT_5":          ["No", "Yes"],
    "FLAG_DOCUMENT_6":          ["No", "Yes"],
    "FLAG_DOCUMENT_7":          ["No", "Yes"],
    "FLAG_DOCUMENT_8":          ["No", "Yes"],
    "FLAG_DOCUMENT_9":          ["No", "Yes"],
    "FLAG_DOCUMENT_10":         ["No", "Yes"],
    "FLAG_DOCUMENT_11":         ["No", "Yes"],
    "FLAG_DOCUMENT_12":         ["No", "Yes"],
    "FLAG_DOCUMENT_13":         ["No", "Yes"],
    "FLAG_DOCUMENT_14":         ["No", "Yes"],
    "FLAG_DOCUMENT_15":         ["No", "Yes"],
    "FLAG_DOCUMENT_16":         ["No", "Yes"],
    "FLAG_DOCUMENT_17":         ["No", "Yes"],
    "FLAG_DOCUMENT_18":         ["No", "Yes"],
    "FLAG_DOCUMENT_19":         ["No", "Yes"],
    "FLAG_DOCUMENT_20":         ["No", "Yes"],
    "FLAG_DOCUMENT_21":         ["No", "Yes"],
    "CREDIT_STATUS":            ["Active", "Repaid", "Written-Off"],
    "CURRENCY_TYPE":            ["Currency X", "Currency Y", "Currency Z"],
    "NUM_CREDIT_EXTENSIONS":    ["None", "Once", "Multiple"],
    "TYPE_OF_CREDIT":           ["Type A", "Type B", "Type C", "Type D"],
    "ACCOUNT_STATUS":           ["On Time", "Delayed", "Defaulted"],
    "CONTRACT_STATUS":          ["Status A", "Status B", "Status C"],
    "LOAN_PURPOSE_CATEGORY":    ["Purpose A", "Purpose B", "Purpose C"],
    "IS_LAST_APPLICATION_FOR_CONTRACT": ["Y", "N"],
    "IS_LAST_APPLICATION_OF_DAY":   ["Y", "N"],
    "PAYMENT_METHOD":           ["Transfer", "Cash", "Wire"],
    "REJECTION_REASON_CODE":    ["Reason X", "Reason Y", "Reason Z"],
    "CLIENT_TYPE":              ["Client A", "Client B"],
    "PORTFOLIO_TYPE":           ["Portfolio A", "Portfolio B"],
    "APPLICATION_CHANNEL":      ["Channel 1", "Channel 2", "Channel 3"],
    "YIELD_CATEGORY":           ["Tier 1", "Tier 2", "Tier 3"],
    "PRODUCT_BUNDLE_TYPE":      ["Combo A", "Combo B", "Combo C"],
    "IS_INSURED_ON_APPROVAL":   ["Y", "N"]
}

DOMAIN_OVERRIDES = {
    # Income & Credit Features
    "MONTHLY_INCOME": {
        "min": 1000,
        "max": 10000,
        "mean": 4000,
        "std": 2000
    },
    "LOAN_AMOUNT": {
        "min": 5000,
        "max": 150000,
        "mean": 30000,
        "std": 20000
    },
    "LOAN_ANNUITY": {
        "min": 200,
        "max": 5000,
        "mean": 1200,
        "std": 700
    },
    "LOAN_TERM_MONTHS": {
        "min": 6,
        "max": 72,
        "mean": 36,
        "std": 15
    },

    # Demographics & Realism Fixes
    "NUM_CHILDREN": {
        "min": 0,
        "max": 6,
        "mean": 1.5,
        "std": 1.2
    },
    "NUM_FAMILY_MEMBERS": {
        "min": 1,
        "max": 10,
        "mean": 3.5,
        "std": 1.5
    },

    # Dates and Durations
    "AGE_DAYS": {
        "min": -25550,   # 70 years
        "max": -6570,    # 18 years
        "mean": -14600,  # 40 years
        "std": 3300
    },
    "EMPLOYMENT_DURATION_DAYS": {
        "min": -14600,   # 40 years
        "max": -30,      # 1 month
        "mean": -3650,   # 10 years
        "std": 2000
    },
    "APPLICATION_HOUR": {
        "min": 0,
        "max": 23,
        "mean": 13,
        "std": 5
    },

    # Housing / Property
    "MAX_FLOORS_AVG": {
        "min": 1,
        "max": 30,
        "mean": 5,
        "std": 4
    },
    "MAX_FLOORS_MODE": {
        "min": 1,
        "max": 30,
        "mean": 5,
        "std": 4
    },
    "MAX_FLOORS_MEDIAN": {
        "min": 1,
        "max": 30,
        "mean": 5,
        "std": 4
    },
    "PROPERTY_TOTAL_AREA": {
        "min": 30,
        "max": 300,
        "mean": 90,
        "std": 50
    },

    # Credit Scores
    "EXTERNAL_CREDIT_SCORE": {
        "min": 0.0,
        "max": 1.0,
        "mean": 0.5,
        "std": 0.2
    },
    "SECONDARY_CREDIT_SCORE": {
        "min": 0.0,
        "max": 1.0,
        "mean": 0.6,
        "std": 0.15
    }
}

