name: loan-predictor-env
channels:
  - defaults
  - conda-forge
dependencies:
  - blinker=1.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - flask=3.1.0
  - flask-cors=5.0.1
  - gunicorn=23.0.0
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - joblib=1.4.2
  - libblas=3.9.0
  - libboost=1.86.0
  - libcblas=3.9.0
  - libcxx=20.1.3
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - liblightgbm=4.6.0
  - liblzma=5.8.1
  - libopenblas=0.3.29
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - llvm-openmp=20.1.3
  - markupsafe=3.0.2
  - ncurses=6.5
  - numpy=2.2.4
  - opencl-headers=2024.10.24
  - openssl=3.5.0
  - packaging=24.2
  - pandas=2.2.3
  - pip=25.0.1
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=78.1.0
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tzdata=2025b
  - urllib3=2.4.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - shap=0.47.2
